DROP TABLE IF EXISTS urls;
DROP SEQUENCE IF EXISTS urls_code_seq;

CREATE SEQUENCE urls_code_seq START WITH 2000;
CREATE TABLE urls(code VARCHAR(50) PRIMARY KEY NOT NULL, url TEXT NOT NULL, visits INTEGER NOT NULL DEFAULT 0);
